### PR TITLE
fix submenu icons width

### PR DESCRIPTION
**Pull request by deniak**
https://github.com/w3c/w3c-website-templates-bundle/pull/128 broke the navigation menu appearance.
That PR fixes the issue.

### CODE REVIEW

**Comment by deniak** [comment]
@koalie noticed that the `columns_with_icons` component is also affected by the SVG alignment, e.g. https://www.w3.org/developers/, https://www.w3.org/get-involved/ or https://www.w3.org/about/.
It seems better to introduce a new class `icon--no-width` we can use to skip the 100% width.

**Review by NicolaSaunders — CHANGES_REQUESTED** [review]
I think it would be simpler to completely remove the nested `:not` statement from the `svg` declaration and add a new declaration below it, as follows:

```
svg:not([class]) {
    width: 100%;
}
```
That way, we don't have to get into the specifics of what class has been added to the svg, nor do we have to introduce a new class.

**Comment by NicolaSaunders** [comment]
@deniak I'll leave that to your discretion, as you will have a better handle on site content than I will 🙂

**Comment by deniak** [comment]
OK, I kept the rule in case I missed a use case.

**Comment by deniak** [comment]
Thanks @NicolaSaunders

**Pull request merged**
