### PR TITLE
fix: wrong spaces and translations in Chinese

### PR DESCRIPTION
**Pull request by kecrily**
## Translation

`login` should be translate as `登录`, not `登陆`. This should be a typo, which is easy to make in Chinese. `登陆` means land.

## Typography

There is no convention for spaces between Chinese and Chinese characters, or between Chinese and Chinese symbols. Using `>-` in yaml's multi-line text results in spaces. See below for the differences:

```diff
-版权所有 © 2023年 [万维网联盟](https://www.w3.org/zh-hans/)。
+版权所有 © 2023年[万维网联盟](https://www.w3.org/zh-hans/)。
-遵循 W3C® [责任声明](https://www.w3.org/policies/#disclaimers)、 [标志使用](https://www.w3.org/policies/#trademarks)以及 [宽松许可](https://www.w3.org/copyright/document-license/)。
+遵循 W3C® [责任声明](https://www.w3.org/policies/#disclaimers)、[标志使用](https://www.w3.org/policies/#trademarks)以及[宽松许可](https://www.w3.org/copyright/document-license/)。
```

### CODE REVIEW

**Comment by japuiglaucia** [comment]
fix: wrong spaces and translations in Chinese #131

**Review by jean-gui — CHANGES_REQUESTED** [review]
Thanks @kecrily for submitting this. Could you  please rebase and regenerate assets to resolve the conflict?

**Comment by kecrily** [comment]
Conflict resolved

**Comment by jean-gui** [comment]
Thanks @kecrily, merged. I'll deploy it soon.

**Pull request merged**
