### PR TITLE
add a user--card class so it can be used outsite a listing

### PR DESCRIPTION
**Pull request by deniak**
Related to the discussion about the ability to use a card outside a listing, that PR adds a new class `user--card` so it doesn't require the `people-list` component.
Comparing with the card from the listing, there are still some margin/padding offsets I'm not sure how to fix.
Also, it's kind of duplicating some rules from the [listing](https://github.com/w3c/w3c-website-templates-bundle/blob/main/assets-src/styles/sass/80-templates/_listing.scss#L28) so I'm not sure it's the best way to handle this.

### CODE REVIEW

**Comment by vivienlacourba** [comment]
> Related to the discussion about the ability to use a card outside a listing, that PR adds a new class `user--card` so it doesn't require the `people-list` component. Comparing with the card from the listing, there are still some margin/padding offsets I'm not sure how to fix. Also, it's kind of duplicating some rules from the [listing](https://github.com/w3c/w3c-website-templates-bundle/blob/main/assets-src/styles/sass/80-templates/_listing.scss#L28) so I'm not sure it's the best way to handle this.

I unfortunately agree that duplicating the CSS rules don't seem to be the proper way to handle this...

**Comment by NicolaSaunders** [comment]
@deniak (cc @vivienlacourba) I have made some adjustments to this pull request. Please could you try pulling them down and see how this works for you?

I have tried to eliminate duplicating styles, but please check that instances of `.card--user` within `.people-list` still appear as you want them to, in addition to an instance of `.card--user` outside of `.people-list`.

Please note that I have had to make some further updates to the NPM packages to be able to compile the CSS.

**Comment by deniak** [comment]
@NicolaSaunders, thanks for the updates. I tested the changes locally and the `.card--user` is working like a charm both within and outside `.people-list`.
I updated the user component accordingly (see https://github.com/w3c/w3c-website-templates-bundle/pull/64/commits/2011fe0d79efac6b47d79f0e5d4dc21e030e20b2).

**Review by NicolaSaunders — APPROVED** [review]

**Comment by NicolaSaunders** [comment]
That's great @deniak - feel free to delete the sections that I commented out in 80-templates/_listing.scss as they won't be needed any longer.

**Comment by deniak** [comment]
> That's great @deniak - feel free to delete the sections that I commented out in 80-templates/_listing.scss as they won't be needed any longer.

oups, I merged too quickly. I removed the comments directly on the main branch (see https://github.com/w3c/w3c-website-templates-bundle/commit/d305737bd63fd0731f591081e508a364d67ac960)

**Pull request merged**
