### PR TITLE
use X instead of Twitter

### PR DESCRIPTION
**Pull request by jean-gui**

### CODE REVIEW

**Comment by jean-gui** [comment]
@xueyuanjia Could you give me the Chinese translation for "W3C on X" that's used as the alt text for the X logo in the footer?

**Review by deniak — APPROVED** [review]

**Comment by xueyuanjia** [comment]
> @xueyuanjia Could you give me the Chinese translation for "W3C on X" that's used as the alt text for the X logo in the footer?

For the alt text for the X logo, I'd translate "W3C on X" into Chinese as "在 X 上关注 W3C".

I see the W3C site footer lists 3 logos. I think it'll be simpler to display the following on the Chinese page: 

“关注 W3C [Mastodon logo] [Twitter (X) logo] [GitHub logo]” which means "Follow W3C on Mastodon, Twitter (X), GitHub".

**Comment by jean-gui** [comment]
> > @xueyuanjia Could you give me the Chinese translation for "W3C on X" that's used as the alt text for the X logo in the footer?
> 
> For the alt text for the X logo, I'd translate "W3C on X" into Chinese as "在 X 上关注 W3C".

For Github and Mastodon we used "W3C 在 Github/Mastodon". I think it's better to use the same format. Can you confirm that "W3C 在 X" is correct?

> I see the W3C site footer lists 3 logos. I think it'll be simpler to display the following on the Chinese page:
> 
> “关注 W3C [Mastodon logo] [Twitter (X) logo] [GitHub logo]” which means "Follow W3C on Mastodon, Twitter (X), GitHub".

My bad, this is not alt text but text for screen readers. As such, I think it's important to keep all three separated.

**Comment by xueyuanjia** [comment]
> For Github and Mastodon we used "W3C 在 Github/Mastodon". I think it's better to use the same format. Can you confirm that "W3C 在 X" is correct?
> 
Yes, “W3C 在 X" also works.

> > I see the W3C site footer lists 3 logos. I think it'll be simpler to display the following on the Chinese page:
> > “关注 W3C [Mastodon logo] [Twitter (X) logo] [GitHub logo]” which means "Follow W3C on Mastodon, Twitter (X), GitHub".
> 
> My bad, this is not alt text but text for screen readers. As such, I think it's important to keep all three separated.

+1 to keep them separated.

Thanks @jean-gui

**Pull request merged**
